name: wms_flutter
description: "WMS Flutter - Warehouse Management System Mobile App"
publish_to: 'none'
version: 1.0.7+8

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  http: ^1.2.2
  shared_preferences: ^2.3.3
  intl: ^0.19.0
  fl_chart: ^0.70.2
  url_launcher: ^6.3.2
  file_picker: ^10.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/wms_logo.png
